### ISSUE TITLE
ZEN-32796 makes zodbscan unusable on 4.x

### ISSUE THREAD

**Issue by cg2v** [zenoss/zenoss.toolbox#139]
`Traceback (most recent call last):
  File "..../toolbox/zodbscan.py", line 28, in <module>
    from zodbpickle.pickle import Unpickler as UnpicklerBase
ImportError: No module named zodbpickle.pickle`

**Comment by nmweizi** [comment]
me to

**Comment by nmweizi** [comment]
pip install zodbpickle
[zenoss@zenoss ~]$ zodbscan
Traceback (most recent call last):
  File "/opt/zenoss/bin/zodbscan", line 8, in <module>
    load_entry_point('zenoss.toolbox==2.3.1', 'console_scripts', 'zodbscan')()
  File "/opt/zenoss/lib/python/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/zenoss/lib/python/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/opt/zenoss/lib/python/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/opt/zenoss/lib/python2.7/site-packages/zenoss.toolbox-2.3.1-py2.7.egg/zenoss/toolbox/zodbscan.py", line 37, in <module>
    from ZODB._compat import PersistentUnpickler
ImportError: No module named _compat
